Question #1 

Given array a = [30, 45, 22, 75, 84] and array b = [67, 40, 90, 13, 56]:

a. For every element e in a and b, calculate and print whether a[e] > b[e].

b. Use a binary mask to change all values where a[e] > 30 to be set to 50.

Question #1 Part a

In [ ]:
import numpy as np

a = np.array([30, 45, 22, 75, 84])
b = np.array([67, 40, 90, 13, 56])

print(a > b)

[False  True False  True  True]


Question #1 Part b

In [ ]:
a[a > 30] = 50
print(a)

[30 50 22 50 50]


Question #2

Given array x = [[5, 2, 6, 1], [3, 4, 7, 2], [8, 1, 2, 9], [3, 4, 2, 6]], calculate the sum of the highlighted and bolded elements using indexing.

In [ ]:
import numpy as np

x = np.array([[5, 2, 6, 1], [3, 4, 7, 2], [8, 1, 2, 9], [3, 4, 2, 6]])
print(x[0,2]+x[3,1])

10


Question #3

Given array c = [[1, 0], [8, 1]] and array d = [[4, 1], [2, 2]], calculate the dot product of c and d.

In [ ]:
import numpy as np

c = np.array([[1, 0], [8, 1]])
d = np.array([[4, 1], [2, 2]])

print(np.dot(c,d))

[[ 4  1]
 [34 10]]


Question #4

Given array a = [[1, 4], [2, 9], [5, 6]], find the shape and transpose of a.

In [ ]:
import numpy as np

a = np.array( [[1, 4], [2, 9], [5, 6]])
print(a.shape)
print(a.T)

(3, 2)
[[1 2 5]
 [4 9 6]]


Question #5

Given array x = [[1, 2], [3, 4]] and array y = [[5, 6], [7, 8], [9, 0]], stack the arrays in sequence vertically.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8], [9, 0]])

print(np.vstack([x,y]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 0]]


Question #6

Calculate the area of x2 + y2 ≤ 1 by uniformly sampling x in [-1,1] and y in [-1,1]

In [1]:
import numpy as np

trial = 1000000
x = np.random.uniform(-1,1,size=trial)
y = np.random.uniform(-1,1,size=trial)

z = x**2+y**2
probability = np.sum(z<=1)/trial
area_of_square = 4
area_of_circle = probability * area_of_square
print(area_of_circle)

3.143104


Question #7

Calculate the probability that x2 + y2 ≤ 1 if x and y are two standard Gaussian distribution variables.

In [ ]:
import numpy as np

trial = 1000000
x = np.random.randn(trial)
y = np.random.randn(trial)

z = x**2+y**2
print(np.sum(z<=1)/trial)

0.39156


Question #8

Calculate the probability that the sum of three dices is larger than 10 if you randomly roll the three dices.

In [ ]:
import numpy as np

trial = 1000000
data = np.random.randint(1,7, size = 3*trial)
#print(data)
each_trial = data.reshape(trial,3)
#print(each_trial)
sum_on_each_trial = each_trial.sum(axis=1)
#print(sum_on_each_trial)
sum_more_than_ten = np.sum(sum_on_each_trial>10)
#print(sum_more_than_ten)
prob = sum_more_than_ten/trial
print(prob)

0.500936
